language: go
go:
    - 1.12.4

env:
  - GO111MODULE=on

script:
    - rm -rf test/indexes
    - rm -rf test/public
    - go test -mod=vendor -v -cover
    - go build -mod=vendor -ldflags "all=-X main.version=$(git describe --tags) -s -w"
    - ./hugo-search -version
