language: go
go:
    - 1.9.2

script:
    - go get github.com/stretchr/testify
    - go get github.com/kardianos/govendor
    - govendor sync
    - go clean
    - rm -rf test/indexes
    - rm -rf test/public
    - go vet -v
    - go test -v -cover
    - go build -ldflags "-X main.version=$(git describe --tags) -s -w"
    - ./hugo-search -version
