language: go
go:
    - 1.14.7

script:
    - rm -rf test/indexes
    - rm -rf test/public
    - go test -mod=vendor -v -cover
    - go build -mod=vendor -ldflags "all=-X main.version=$(git describe --tags) -s -w"
    - ./hugo-search -version
