language: go
go:
    - 1.12.4

script:
    - rm -rf test/indexes
    - rm -rf test/public
    - go vet -v
    - go test -v -cover
    - go build -mod=vendor -ldflags "all=-X main.version=$(git describe --tags) -s -w"
    - ./hugo-search -version
